<a href="https://colab.research.google.com/github/2303A51337Srivarsha/Reinforcementlearning/blob/main/1337_RL_A2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
M = input("enter number of machines")
M = int(M)

machines = []

for i in range(M):
    name = input("enter machine name")
    machines.append(name)

print(machines)

enter number of machines3
enter machine nameA
enter machine nameB
enter machine nameC
['A', 'B', 'C']


In [2]:
import numpy as np
N_play = 3
N = np.zeros((M, N_play+1))
R = np.zeros((M, N_play+1))
Q_value = np.zeros((M, N_play+1))
Q_old = [0, 0, 0]
for machine in machines:
    print(f"Play with machine {machine}")
    r = input("enter reward")
    r = int(r)
    id = machines.index(machine)
    N[id, 0] = 1
    R[id, 0] = r
    Q_value[id, 0] = Q_old[id] + (R[id, 0] - Q_old[id]) / N[id, 0]
print(Q_value)
print(N)
print(R)

Play with machine A
enter reward3
Play with machine B
enter reward6
Play with machine C
enter reward4
[[3. 0. 0. 0.]
 [6. 0. 0. 0.]
 [4. 0. 0. 0.]]
[[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]]
[[3. 0. 0. 0.]
 [6. 0. 0. 0.]
 [4. 0. 0. 0.]]


In [4]:
import random

eps = 0.2
play = 1

while play <= N_play:

    Q_value[:, play] = Q_value[:, play - 1]

    r = random.uniform(0, 1)

    if r < eps:

        print("Explore")

        id = random.randint(0, M - 1)

        print(f"Play with machine {machines[id]}")

        r = input("enter reward")
        r = int(r)

        N[id, play] = 1
        R[id, play] = r
        Q_value[id, play] = Q_value[id, play - 1] + (
            R[id, play] - Q_value[id, play - 1]
        ) / np.sum(N[id, :])

    else:

        print("Exploit")

        id = np.argmax(Q_value[:, play - 1])

        print(f"Play with machine {machines[id]}")

        r = input("enter reward")
        r = int(r)

        N[id, play] = 1
        R[id, play] = r

        Q_value[id, play] = Q_value[id, play - 1] + (
            R[id, play] - Q_value[id, play - 1]
        ) / np.sum(N[id, :])

    play = play + 1
    print(Q_value)
print("=" * 50)
print("Participation of each machine in each play")
print("=" * 50)
print(N)

print("=" * 50)
print("Rewards of each machine in each play")
print("=" * 50)
print(R)

print("=" * 50)
print("Estimated future Rewards of each machine")
print("=" * 50)
print(Q_value)

Exploit
Play with machine B
enter reward4
[[3. 3. 0. 0.]
 [6. 5. 0. 0.]
 [4. 4. 0. 0.]]
Exploit
Play with machine B
enter reward7
[[3.         3.         3.         0.        ]
 [6.         5.         5.66666667 0.        ]
 [4.         4.         4.         0.        ]]
Exploit
Play with machine B
enter reward5
[[3.         3.         3.         3.        ]
 [6.         5.         5.66666667 5.5       ]
 [4.         4.         4.         4.        ]]
Participation of each machine in each play
[[1. 0. 0. 0.]
 [1. 1. 1. 1.]
 [1. 0. 0. 0.]]
Rewards of each machine in each play
[[3. 0. 0. 0.]
 [6. 4. 7. 5.]
 [4. 0. 0. 0.]]
Estimated future Rewards of each machine
[[3.         3.         3.         3.        ]
 [6.         5.         5.66666667 5.5       ]
 [4.         4.         4.         4.        ]]


In [5]:
total_reward = np.sum(R[:, 1:])
number_of_plays = np.sum(N[:, 1:])

average_reward = total_reward / number_of_plays

print("=" * 50)
print("Total ε-Greedy Reward =", int(total_reward))
print("Average ε-Greedy Reward =", round(average_reward, 2))


Total ε-Greedy Reward = 16
Average ε-Greedy Reward = 5.33
