<a href="https://colab.research.google.com/github/2303A51337Srivarsha/Reinforcementlearning/blob/main/RL_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

MODIFIED E-GREEDY

In [1]:
M=input("enter number of machines")
M=int(M)

machines=[]

for i in range(M):
    name=input("enter machine name")
    machines.append(name)

print(machines)


enter number of machines3
enter machine nameA
enter machine nameB
enter machine nameC
['A', 'B', 'C']


In [2]:
import numpy as np

N_plays = 3

N = np.zeros((M, N_plays))
R = np.zeros((M, N_plays))
Q = np.zeros((M, N_plays))

for machine in machines:
    print(f"Play with machine {machine}")

    reward = input("enter reward")
    reward = int(reward)

    id = machines.index(machine)

    N[id, 0] = 1
    R[id, 0] = reward

    Q[id, 0] = Q[id, 0] + (R[id, 0] - Q[id, 0]) / N[id, 0]

print(R)
print(N)
print(Q)

Play with machine A
enter reward3
Play with machine B
enter reward6
Play with machine C
enter reward4
[[3. 0. 0.]
 [6. 0. 0.]
 [4. 0. 0.]]
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
[[3. 0. 0.]
 [6. 0. 0.]
 [4. 0. 0.]]


In [3]:


import random

eps = 0.2
play = 1

while(play <= N_plays - 1):

    r = random.uniform(0, 1)

    id_max = np.argmax(Q[:, play - 1])

    if(r < eps):
        print("Exploration")

        ids = [i for i in range(M) if i != id_max] # except max value ramdomly choose any (modified e-greedy),whereas in E-greedy max value is also included

        id = random.choice(ids)

        print(f"Now select machine {machines[id]}")

        reward = input("enter reward")
        reward = int(reward)

        Q[:, play] = Q[:, play - 1]

        R[id, play] = reward
        N[id, play] = 1

        Q[id, play] = Q[id, play - 1] + (
            R[id, play] - Q[id, play - 1]
        ) / np.sum(N[id, :])

    else:
        print("Exploitation")

        id = id_max

        print(f"Now select machine {machines[id]}")

        reward = input("enter reward")
        reward = int(reward)

        Q[:, play] = Q[:, play - 1]

        R[id, play] = reward
        N[id, play] = 1

        Q[id, play] = Q[id, play - 1] + (
            R[id, play] - Q[id, play - 1]
        ) / np.sum(N[id, :])

    play = play + 1
    print(R)
    print(N)
    print(Q)

Exploitation
Now select machine B
enter reward7
[[3. 0. 0.]
 [6. 7. 0.]
 [4. 0. 0.]]
[[1. 0. 0.]
 [1. 1. 0.]
 [1. 0. 0.]]
[[3.  3.  0. ]
 [6.  6.5 0. ]
 [4.  4.  0. ]]
Exploration
Now select machine C
enter reward5
[[3. 0. 0.]
 [6. 7. 0.]
 [4. 0. 5.]]
[[1. 0. 0.]
 [1. 1. 0.]
 [1. 0. 1.]]
[[3.  3.  3. ]
 [6.  6.5 6.5]
 [4.  4.  4.5]]


In [4]:
total_reward = np.sum(R[:, 1:])
number_of_plays = np.sum(N[:, 1:])

average_reward = total_reward / number_of_plays

print("=" * 50)
print("Total ε-Greedy Reward =", int(total_reward))
print("Average ε-Greedy Reward =", round(average_reward, 2))

Total ε-Greedy Reward = 12
Average ε-Greedy Reward = 6.0


Calculate total reward the player received

In [5]:
total_reward = np.sum(R)
total_count = np.sum(N)

average_reward = total_reward / total_count

print("Total Reward =", int(total_reward))
print("Average Reward =", round(average_reward, 2))

Total Reward = 25
Average Reward = 5.0
